import { ready, t } from "/js/i18n.js";
import { getSupabase, isConfigReady } from "/js/supabase-client.js";
const GAME_ID="lucky-lounge", DAILY=100, MULT=[.2,.4,.7,1,1.2,1,.7,.4,.2];
const $=id=>document.getElementById(id), chips=$("chips"),claim=$("claim"),drop=$("drop"),bet=$("bet"),ball=$("ball"),board=$("plinko"),pegs=$("pegs"),bins=$("bins"),message=$("message");
let user, state={chips:0,lastClaimDay:"",spins:0,biggestWin:0}, busy=false;
const day=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Berlin"}).format(new Date());
function render(){chips.textContent=new Intl.NumberFormat().format(state.chips);claim.disabled=state.lastClaimDay===day();claim.textContent=claim.disabled?t("lounge.claimed"):t("lounge.claim");}
async function save(){const {error}=await getSupabase().from("game_saves").upsert({user_id:user.id,game_id:GAME_ID,payload:state,total_earned:state.biggestWin,display_name:"Spieler",updated_at:new Date().toISOString()});if(error)message.textContent=t("lounge.save_failed");}
function setup(){pegs.innerHTML=Array.from({length:45},()=>'<i class="peg"></i>').join("");bins.innerHTML=MULT.map((m,i)=>`<div class="bin ${i===4?"hot":""}">${m}×</div>`).join("");}
async function claimDaily(){if(state.lastClaimDay===day())return;state.chips+=DAILY;state.lastClaimDay=day();message.textContent=t("lounge.claimed_message",{value:DAILY});render();await save();}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function play(){const stake=Math.floor(Number(bet.value));if(busy||!Number.isFinite(stake)||stake<1||stake>state.chips){message.textContent=t("lounge.invalid_bet");return;}busy=true;drop.disabled=true;state.chips-=stake;let slot=4;ball.hidden=false;ball.style.left="50%";ball.style.top="5%";for(let row=0;row<8;row++){slot+=Math.random()<.5?-1:1;slot=Math.max(0,Math.min(8,slot));ball.style.left=`${(slot+.5)/9*100}%`;ball.style.top=`${10+row*9}%`;await wait(145);}await wait(160);const mult=MULT[slot],win=Math.floor(stake*mult);state.chips+=win;state.spins++;state.biggestWin=Math.max(state.biggestWin,win);message.textContent=t("lounge.result",{mult:mult.toFixed(1),value:win});render();await save();await wait(700);ball.hidden=true;busy=false;drop.disabled=false;}
async function boot(){await ready;if(!isConfigReady()){location.replace("/login.html");return;}const client=getSupabase(),result=await client.auth.getSession();user=result.data.session?.user;if(!user){location.replace(`/login.html?next=${encodeURIComponent(location.pathname)}`);return;}const loaded=await client.from("game_saves").select("payload").eq("user_id",user.id).eq("game_id",GAME_ID).maybeSingle();if(loaded.data?.payload)state={...state,...loaded.data.payload};setup();render();claim.addEventListener("click",claimDaily);drop.addEventListener("click",play);}boot();
