export const buildings = [
  { id: "seedling", name: "Mini-Kaktus", icon: "K", baseCost: 15, cps: 0.1, description: "Kleine Produktion für den Anfang." },
  { id: "greenhouse", name: "Gewächshaus", icon: "G", baseCost: 100, cps: 1, description: "Mehr Kakteen aus kontrolliertem Anbau." },
  { id: "ranch", name: "Kaktus-Ranch", icon: "R", baseCost: 1100, cps: 8, description: "Reihenweise Kakteen für den nächsten Schub." },
  { id: "oasis", name: "Oasenpumpe", icon: "O", baseCost: 12000, cps: 47, description: "Stabile Ernte auch im trockenen Boden." },
  { id: "factory", name: "Stachelwerk", icon: "F", baseCost: 130000, cps: 260, description: "Industrielle Produktion für große Zahlen." },
  { id: "harvest-drone", name: "Erntedrohne", icon: "D", baseCost: 1400000, cps: 1400, description: "Automatisiert die schnelle Ernte." },
  { id: "lab", name: "Kaktuslabor", icon: "L", baseCost: 20000000, cps: 7800, description: "Züchtet stärkere Produktionslinien." },
  { id: "server-farm", name: "Wüstenserver", icon: "S", baseCost: 330000000, cps: 44000, description: "Optimiert jeden Produktionszyklus." },
  { id: "orbital-greenhouse", name: "Orbit-Gewächshaus", icon: "O", baseCost: 5100000000, cps: 260000, description: "Kakteenproduktion ohne Tageslimit." },
  { id: "monsoon-rig", name: "Monsun-Rig", icon: "M", baseCost: 75000000000, cps: 1600000, description: "Zieht Feuchtigkeit aus jedem Sturm." },
  { id: "canyon-refinery", name: "Canyon-Raffinerie", icon: "C", baseCost: 1000000000000, cps: 10000000, description: "Presst jeden Tropfen in Wachstum." },
  { id: "plasma-irrigation", name: "Plasma-Bewässerung", icon: "P", baseCost: 14000000000000, cps: 65000000, description: "Lädt Wurzeln mit Neonenergie." },
  { id: "lunar-nursery", name: "Mondgärtnerei", icon: "M", baseCost: 170000000000000, cps: 420000000, description: "Pflegt Kakteen unter kaltem Licht." },
  { id: "asteroid-hacienda", name: "Asteroiden-Hacienda", icon: "A", baseCost: 2100000000000000, cps: 2800000000, description: "Erntet zwischen schwebenden Felsen." },
  { id: "solar-silo", name: "Solarsilo", icon: "S", baseCost: 26000000000000000, cps: 18000000000, description: "Speichert Glut für endlose Ernten." },
  { id: "quantum-spine", name: "Quantenstachel", icon: "Q", baseCost: 310000000000000000, cps: 120000000000, description: "Verdoppelt Ernten in Nebenpfaden." },
  { id: "nebula-pipeline", name: "Nebula-Pipeline", icon: "N", baseCost: 3700000000000000000, cps: 790000000000, description: "Schickt Kaktussaft durch Sternennebel." },
  { id: "rift-garden", name: "Rissgarten", icon: "R", baseCost: 44000000000000000000, cps: 5200000000000, description: "Lässt Dornen aus Parallelräumen wachsen." },
  { id: "prism-foundry", name: "Prisma-Gießerei", icon: "P", baseCost: 520000000000000000000, cps: 34000000000000, description: "Gießt Licht in neue Pflanzenformen." },
  { id: "void-terrace", name: "Void-Terrasse", icon: "V", baseCost: 6200000000000000000000, cps: 220000000000000, description: "Blüht dort, wo sonst nichts lebt." },
  { id: "starloom", name: "Sternwebstuhl", icon: "S", baseCost: 74000000000000000000000, cps: 1450000000000000, description: "Webt Ernteketten aus Sternenstaub." },
  { id: "thorn-reactor", name: "Dornenreaktor", icon: "D", baseCost: 890000000000000000000000, cps: 9600000000000000, description: "Hält die Wüste dauerhaft kritisch." },
  { id: "chrono-orchard", name: "Chrono-Orchard", icon: "C", baseCost: 1.07e25, cps: 6.3e16, description: "Erntet mehrere Sekunden zugleich." },
  { id: "singularity-nursery", name: "Singularitätsgarten", icon: "S", baseCost: 1.28e26, cps: 4.2e17, description: "Zieht Wachstum in einen grünen Kern." },
  { id: "galaxy-vault", name: "Galaxie-Tresor", icon: "G", baseCost: 1.54e27, cps: 2.8e18, description: "Lagert Ernten über ganze Spiralen." },
  { id: "mythic-desert", name: "Mythische Wüste", icon: "M", baseCost: 1.85e28, cps: 1.85e19, description: "Macht Legenden zu Produktion." },
  { id: "cactus-matrix", name: "Kaktus-Matrix", icon: "X", baseCost: 2.22e29, cps: 1.22e20, description: "Berechnet Wachstum vor dem Klick." },
  { id: "nopal-ark", name: "Nopal-Arche", icon: "N", baseCost: 2.66e30, cps: 8.1e20, description: "Trägt Dornen durch jede Saison." },
  { id: "cosmic-root", name: "Kosmische Wurzel", icon: "K", baseCost: 3.19e31, cps: 5.4e21, description: "Verankert Ernte in tiefem Raum." },
  { id: "endless-bloom", name: "Endlosblüte", icon: "E", baseCost: 3.83e32, cps: 3.6e22, description: "Wächst weiter, wenn Zahlen verschwimmen." },
];

const legacyUpgrades = [
  { id: "gloves", name: "Dicke Handschuhe", icon: "H", cost: 100, description: "Klick-Ertrag x2.", clickMultiplier: 2 },
  { id: "soft-gloves", name: "Weiche Handschuhe", icon: "W", cost: 500, description: "Klick-Ertrag x2.", clickMultiplier: 2 },
  { id: "sun-map", name: "Doppelte Zange", icon: "Z", cost: 10000, description: "Klick-Ertrag x2.", clickMultiplier: 2 },
  { id: "seedling-pots", name: "Stabile Töpfe", icon: "K", cost: 100, description: "Mini-Kaktus Produktion x2.", buildingId: "seedling", buildingMultiplier: 2 },
  { id: "greenhouse-glass", name: "Klares Glas", icon: "G", cost: 1000, description: "Gewächshaus Produktion x2.", buildingId: "greenhouse", buildingMultiplier: 2 },
  { id: "ranch-irrigation", name: "Ranch-Bewässerung", icon: "R", cost: 11000, description: "Kaktus-Ranch Produktion x2.", buildingId: "ranch", buildingMultiplier: 2 },
  { id: "oasis-pressure", name: "Hochdruckpumpe", icon: "O", cost: 120000, description: "Oasenpumpe Produktion x2.", buildingId: "oasis", buildingMultiplier: 2 },
  { id: "factory-lines", name: "Doppelschicht", icon: "F", cost: 1300000, description: "Stachelwerk Produktion x2.", buildingId: "factory", buildingMultiplier: 2 },
  { id: "drone-bay", name: "Drohnenhangar", icon: "D", cost: 14000000, description: "Erntedrohne Produktion x2.", buildingId: "harvest-drone", buildingMultiplier: 2 },
  { id: "lab-culture", name: "Schnellkultur", icon: "L", cost: 200000000, description: "Kaktuslabor Produktion x2.", buildingId: "lab", buildingMultiplier: 2 },
  { id: "server-cluster", name: "Servercluster", icon: "S", cost: 3300000000, description: "Wüstenserver Produktion x2.", buildingId: "server-farm", buildingMultiplier: 2 },
  { id: "orbital-cycle", name: "Orbit-Zyklus", icon: "O", cost: 51000000000, description: "Orbit-Gewächshaus Produktion x2.", buildingId: "orbital-greenhouse", buildingMultiplier: 2 },
];

const newBuildingUpgrades = buildings.slice(9).map((building, index) => ({
  id: `${building.id}-core`,
  name: `${building.name} Kern`,
  icon: building.icon,
  cost: Math.ceil(building.baseCost * (9 + (index % 4))),
  description: `${building.name} Produktion x2.`,
  buildingId: building.id,
  buildingMultiplier: 2,
}));

export const upgrades = [
  ...legacyUpgrades,
  ...newBuildingUpgrades,
];

export const achievements = [
  { id: "first-click", name: "Erster Stich", goal: "Ernte deinen ersten Kaktus.", test: (state) => state.totalClicks >= 1 },
  { id: "hundred-clicks", name: "Klickroutine", goal: "Klicke 100 Mal manuell.", test: (state) => state.totalClicks >= 100 },
  { id: "thousand-clicks", name: "Goldfinger", goal: "Klicke 1.000 Mal manuell.", test: (state) => state.totalClicks >= 1000 },
  { id: "five-thousand-clicks", name: "Handarbeit", goal: "Klicke 5.000 Mal manuell.", test: (state) => state.totalClicks >= 5000 },
  { id: "twenty-five-thousand-clicks", name: "Dornenmaschine", goal: "Klicke 25.000 Mal manuell.", test: (state) => state.totalClicks >= 25000 },
  { id: "hundred-thousand-clicks", name: "Klicklegende", goal: "Klicke 100.000 Mal manuell.", test: (state) => state.totalClicks >= 100000 },
  { id: "hundred-earned", name: "Kleiner Garten", goal: "Ernte insgesamt 100 Kakteen.", test: (state) => state.totalEarned >= 100 },
  { id: "thousand-earned", name: "Grüne Welle", goal: "Ernte insgesamt 1.000 Kakteen.", test: (state) => state.totalEarned >= 1000 },
  { id: "million-earned", name: "Millionenernte", goal: "Ernte insgesamt 1 Mio. Kakteen.", test: (state) => state.totalEarned >= 1e6 },
  { id: "billion-earned", name: "Milliardenfeld", goal: "Ernte insgesamt 1 Mrd. Kakteen.", test: (state) => state.totalEarned >= 1e9 },
  { id: "trillion-earned", name: "Billionenblüte", goal: "Ernte insgesamt 1 Bio. Kakteen.", test: (state) => state.totalEarned >= 1e12 },
  { id: "quintillion-earned", name: "Trillionenwüste", goal: "Ernte insgesamt 1 Trio. Kakteen.", test: (state) => state.totalEarned >= 1e18 },
  { id: "quintilliarde-earned", name: "Quintillionengrün", goal: "Ernte insgesamt 1 Quinto. Kakteen.", test: (state) => state.totalEarned >= 1e30 },
  { id: "first-prestige", name: "Erste Nopal-Ernte", goal: "Führe dein erstes Prestige durch.", test: (state) => state.prestige.prestiges >= 1 },
  { id: "ten-nopal", name: "Nopal-Puffer", goal: "Sammle 10 Nopal in dieser Saison.", test: (state) => state.prestige.totalNopalEarned >= 10 },
  { id: "ten-prestiges", name: "Saisonschleife", goal: "Führe 10 Prestiges durch.", test: (state) => state.prestige.prestiges >= 10 },
  { id: "first-frenzy", name: "Goldener Lauf", goal: "Fülle den Klick-Balken einmal.", test: (state) => state.events.frenzies >= 1 },
  { id: "golden-hit", name: "Goldkaktus", goal: "Fange einen Goldkaktus.", test: (state) => state.events.goldenHits >= 1 },
  { id: "golden-hunter", name: "Goldjäger", goal: "Fange 10 Goldkakteen.", test: (state) => state.events.goldenHits >= 10 },
  { id: "red-hit", name: "Rubinkaktus", goal: "Fange einen Rubinkaktus.", test: (state) => state.events.redHits >= 1 },
];

export const changelogEntries = [
  {
    date: "22.05.2026",
    title: "Audio & Feinschliff",
    items: [
      "Minor bug fixes and UI improvements.",
      "Added SFX and music.",
      "Gold- und Rubinkakteen reagieren nur auf aktive Spielzeit.",
      "Mobile Webapp-Layout und Touch-Verhalten verbessert.",
    ],
  },
  {
    date: "22.05.2026",
    title: "Prestige-Update",
    items: [
      "Nopal-Prestige beschleunigt neue Runs innerhalb der laufenden Saison.",
      "Goldlauf, Goldkakteen und seltene Rubinkakteen belohnen aktives Spielen.",
      "Offline-Fortschritt sammelt ab 5 Minuten bis zu 12 Stunden halbe automatische Produktion ein.",
      "Neue Gebäude, neue Upgrades und 20 Abzeichen erweitern den Grind nach oben.",
      "Die Rangliste läuft jetzt monatlich und zeigt den letzten Monatsabschluss.",
      "Große Zahlen werden im deutschen Format mit lesbaren Abkürzungen angezeigt.",
    ],
  },
];
